# Copyright (c) 2016-2026 Makerdiary <https://makerdiary.com>
# SPDX-License-Identifier: Apache-2.0

manifest:
  self: 
    path: nrf9151-connectkit

  remotes:
    - name: makerdiary
      url-base: https://github.com/makerdiary
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: 95ed8f7e7406e4d2d93c99f81c88e45178813e9a
      import: true
