# General
CONFIG_REBOOT=y
CONFIG_POWEROFF=y
CONFIG_DK_LIBRARY=y
CONFIG_GPIO=y
CONFIG_SENSOR=y
CONFIG_PM_DEVICE=y
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_HW_STACK_PROTECTION=n
CONFIG_RESET_ON_FATAL_ERROR=y

# USB
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_SAMPLE_USBD_MANUFACTURER="Makerdiary"
CONFIG_SAMPLE_USBD_PRODUCT="IFMCU CMSIS-DAP"
CONFIG_SAMPLE_USBD_PID=0x0204
CONFIG_SAMPLE_USBD_20_EXTENSION_DESC=y

# UART
CONFIG_UART_BRIDGE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

# DAP
CONFIG_DAP=y
CONFIG_DAP_BACKEND_USB=n
CONFIG_CMSIS_DAP_BOARD_VENDOR="Makerdiary"
CONFIG_CMSIS_DAP_BOARD_NAME="nRF9151 Connect Kit"
CONFIG_CMSIS_DAP_DEVICE_VENDOR="Nordic Semiconductor ASA"
CONFIG_CMSIS_DAP_DEVICE_NAME="NRF91"

# Shell
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=2048
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=y
CONFIG_SHELL_PROMPT_UART="ifsh:~$ "
CONFIG_APP_VERSION_SHELL=n
CONFIG_DATE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_I2C_SHELL=y
CONFIG_SETTINGS_SHELL=y

# Settings
CONFIG_FCB=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_FCB=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Logging
CONFIG_LOG=n
