contact_links:
  - name: Makerdiary Official Store
    url: https://makerdiary.com
    about: If you want to order our hardware, visit here.
  - name: Makerdiary Tech Support
    url: https://community.makerdiary.com
    about: If you have other questions or need help, post it here.
