# Copyright (c) 2016-2025 Makerdiary <https://makerdiary.com>
name: Twister Apps & Samples

on:
  push:
  pull_request:
  schedule:
    # Run at 03:00 UTC on every Sunday
    - cron: "0 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: nrf9151-connectkit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nrf9151-connectkit
          toolchains: arm-zephyr-eabi

      - name: Twister Applications
        working-directory: nrf9151-connectkit
        shell: bash
        run: |
          west twister -T applications -v --inline-logs --integration

      - name: Twister Samples
        working-directory: nrf9151-connectkit
        shell: bash
        run: |
          west twister -T samples -v --inline-logs --integration
